"""add role column to users

Revision ID: 751768469d4e
Revises: 7c6a99a345a2
Create Date: 2025-10-18 14:56:47.690983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751768469d4e'
down_revision = '7c6a99a345a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
